package example;

import com.amazonaws.services.dynamodbv2.datamodeling.*;


@DynamoDBTable(tableName="Question")
public class Pytanie {

    private String id;

    private String question;
    private String answer;
    private String context;
    public Pytanie(String id, String question, String answer, String context) {
        this.id = id;
        this.question = question;
        this.answer = answer;
        this.context = context;
    }

    public Pytanie(){}



    //@DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String  id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "question")
    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    @DynamoDBAttribute(attributeName = "answer")
    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    @DynamoDBAttribute(attributeName = "context")
    public String getContext() {
        return context;
    }

    public void setContext(String context) {
        this.context = context;
    }

    public static Pytanie findQuestion(String id,DynamoDBMapper mapper){
        Pytanie p = mapper.load(Pytanie.class, id);

        return p;
    }

    public static void addQuestion(String id, String question, String answer, String context, DynamoDBMapper mapper){
        Pytanie p = new Pytanie(id, question, answer, context);
        mapper.save(p);
    }

    public static void deleteQuestion(String id, DynamoDBMapper mapper){
        Pytanie p = findQuestion(id, mapper);
        mapper.delete(p);
    }
}
