package example;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.LinkedList;
import java.util.List;

@DynamoDBTable(tableName="Test")
public class Test {

    private String id;
    private String candidate;
    private String recruter;
    private String title;
    private List<Question> questions = new LinkedList<Question>();
    private String points;



    public Test(){}

    public Test(String id, String candidate, String recruter, String title, List<Question> questions, String points) {
        this.id = id;
        this.candidate = candidate;
        this.recruter = recruter;
        this.title = title;
        this.questions = questions;
        this.points = points;
    }
//
//    public Test(String id, String candidate, List<Pytanie> questions) {
//        this.id = id;
//        this.candidate = candidate;
//        this.questions = questions;
//    }

    @DynamoDBHashKey(attributeName="id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName="points")
    public String getPoints() {
        return points;
    }
    public void setPoints(String points) {
        this.points = points;
    }

    @DynamoDBAttribute(attributeName="candidate")
    public String getCandidate() {
        return candidate;
    }
    public void setCandidate(String candidate) {
        this.candidate = candidate;
    }

    @DynamoDBAttribute(attributeName="title")
    public String getTitle() {
        return title;
    }
    public void setTitle(String title) {
        this.title = title;
    }


    @DynamoDBAttribute(attributeName="questions")
    public List<Question> getQuestions() {
        return questions;
    }
    public void setQuestions(List<Question> questions) {
        this.questions = questions;
    }

    public static Test findTest(String id,DynamoDBMapper mapper){
        Test t = mapper.load(Test.class, id);

        return t;
    }

//

    public static void deleteTest(String id, DynamoDBMapper mapper){
        Test t = findTest(id, mapper);
        mapper.delete(t);
    }
    @DynamoDBAttribute(attributeName="recruter")
    public String getRecruter() {
        return recruter;
    }
    public void setRecruter(String recruter) {
        this.recruter = recruter;
    }
}
